default_install_hook_types: [pre-commit, pre-merge-commit, pre-push, post-merge, post-checkout]
repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        # args: ["-ignore", "SC2129"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-added-large-files
        args:
          - "--maxkb=1024"
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        # exclude: 'infra/terraform/.*/README\.md$'
      - id: detect-private-key
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
      - id: mixed-line-ending
  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos
        args:
          - "--force-exclude"
          - "--write-changes"
